#import <PEGKit/PKParser.h>
        
@class PKTokenizer;

enum {
    XP_TOKEN_KIND_GE = 14,
    XP_TOKEN_KIND_DOUBLE_PIPE = 15,
    XP_TOKEN_KIND_MINUS = 16,
    XP_TOKEN_KIND_GE_SYM = 17,
    XP_TOKEN_KIND_SEMI_COLON = 18,
    XP_TOKEN_KIND_DOUBLE_AMPERSAND = 19,
    XP_TOKEN_KIND_LT_SYM = 20,
    XP_TOKEN_KIND_NOT_EQUAL = 21,
    XP_TOKEN_KIND_DIV = 22,
    XP_TOKEN_KIND_EQUALS = 23,
    XP_TOKEN_KIND_BANG = 24,
    XP_TOKEN_KIND_OR = 25,
    XP_TOKEN_KIND_GT_SYM = 26,
    XP_TOKEN_KIND_DOT = 27,
    XP_TOKEN_KIND_NE = 28,
    XP_TOKEN_KIND_TRUE = 29,
    XP_TOKEN_KIND_LE_SYM = 30,
    XP_TOKEN_KIND_AND = 31,
    XP_TOKEN_KIND_MOD = 32,
    XP_TOKEN_KIND_LT = 33,
    XP_TOKEN_KIND_FALSE = 34,
    XP_TOKEN_KIND_LE = 35,
    XP_TOKEN_KIND_NOT = 36,
    XP_TOKEN_KIND_OPEN_PAREN = 37,
    XP_TOKEN_KIND_DOUBLE_EQUALS = 38,
    XP_TOKEN_KIND_EQ = 39,
    XP_TOKEN_KIND_GT = 40,
    XP_TOKEN_KIND_CLOSE_PAREN = 41,
    XP_TOKEN_KIND_TIMES = 42,
    XP_TOKEN_KIND_PLUS = 43,
    XP_TOKEN_KIND_VAR = 44,
};

@interface XPParser : PKParser
        
+ (PKTokenizer *)tokenizer;

@property (nonatomic, assign) BOOL allowNakedExpressions;

@end

