#import <PEGKit/PKParser.h>
        
    
#define XP_TOKEN_KIND_BLOCK -2
#define XP_TOKEN_KIND_CALL  -3
#define XP_TOKEN_KIND_APPEND -4
#define XP_TOKEN_KIND_SAVE_SUBSCRIPT -5
#define XP_TOKEN_KIND_LOAD_SUBSCRIPT -6
#define XP_TOKEN_KIND_NEG -7
#define XP_TOKEN_KIND_LOAD -8
#define XP_TOKEN_KIND_FUNC_LITERAL -9
#define XP_TOKEN_KIND_ARRAY_LITERAL -10
#define XP_TOKEN_KIND_DICT_LITERAL -11

@class PKTokenizer;
@class XPGlobalScope;
@class XPMemorySpace;
@protocol XPScope;

enum {
    XP_TOKEN_KIND_OPEN_CURLY = 14,
    XP_TOKEN_KIND_GE = 15,
    XP_TOKEN_KIND_BITOR = 16,
    XP_TOKEN_KIND_TIMESEQ = 17,
    XP_TOKEN_KIND_IS = 18,
    XP_TOKEN_KIND_BREAK = 19,
    XP_TOKEN_KIND_FOR = 20,
    XP_TOKEN_KIND_RETURN = 21,
    XP_TOKEN_KIND_CLOSE_CURLY = 22,
    XP_TOKEN_KIND_SHIFTRIGHT = 23,
    XP_TOKEN_KIND_PLUSEQ = 24,
    XP_TOKEN_KIND_NE = 25,
    XP_TOKEN_KIND_IF = 26,
    XP_TOKEN_KIND_ELSE = 27,
    XP_TOKEN_KIND_BANG = 28,
    XP_TOKEN_KIND_BITNOT = 29,
    XP_TOKEN_KIND_CONTINUE = 30,
    XP_TOKEN_KIND_COLON = 31,
    XP_TOKEN_KIND_TRUE = 32,
    XP_TOKEN_KIND_SEMI_COLON = 33,
    XP_TOKEN_KIND_LT = 34,
    XP_TOKEN_KIND_MINUSEQ = 35,
    XP_TOKEN_KIND_MOD = 36,
    XP_TOKEN_KIND_EQUALS = 37,
    XP_TOKEN_KIND_BITAND = 38,
    XP_TOKEN_KIND_GT = 39,
    XP_TOKEN_KIND_OPEN_PAREN = 40,
    XP_TOKEN_KIND_WHILE = 41,
    XP_TOKEN_KIND_VAR = 42,
    XP_TOKEN_KIND_CLOSE_PAREN = 43,
    XP_TOKEN_KIND_DIVEQ = 44,
    XP_TOKEN_KIND_TIMES = 45,
    XP_TOKEN_KIND_OR = 46,
    XP_TOKEN_KIND_CAT = 47,
    XP_TOKEN_KIND_PLUS = 48,
    XP_TOKEN_KIND_NOT = 49,
    XP_TOKEN_KIND_OPEN_BRACKET = 50,
    XP_TOKEN_KIND_COMMA = 51,
    XP_TOKEN_KIND_AND = 52,
    XP_TOKEN_KIND_NULL = 53,
    XP_TOKEN_KIND_MINUS = 54,
    XP_TOKEN_KIND_IN = 55,
    XP_TOKEN_KIND_CLOSE_BRACKET = 56,
    XP_TOKEN_KIND_NAN = 57,
    XP_TOKEN_KIND_SHIFTLEFT = 58,
    XP_TOKEN_KIND_BITXOR = 59,
    XP_TOKEN_KIND_DIV = 60,
    XP_TOKEN_KIND_FALSE = 61,
    XP_TOKEN_KIND_SUB = 62,
    XP_TOKEN_KIND_LE = 63,
    XP_TOKEN_KIND_EQ = 64,
};

@interface XPParser : PKParser
        
+ (PKTokenizer *)tokenizer;

@property (nonatomic, retain) id <XPScope>currentScope;
@property (nonatomic, retain) XPGlobalScope *globalScope;
@property (nonatomic, retain) XPMemorySpace *globals;
@property (nonatomic, assign) BOOL foundDefaultParam;

@end

